![](G1.jpg)

In [18]:
#Membuat 0 dan Merubah Menjadi 0-4

In [136]:
import numpy as np 

In [157]:
a=np.zeros(shape=(5,5))
print (a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [158]:
a=a+np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])